---
title: "Historia"
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: true
      smooth_scroll: true
---


#**Antecedentes **

####**¿Cuál es el panorama económico de el comercio de miel en México? **
México produce 57,995 toneladas de miel en promedio por año (periodo 2014-2018) y es el octavo productor a nivel mundial. Mientras que la mitad de la producción se consume a nivel nacional, el consumo anual per cápita es de alrededor de 300 gramos y el país continúa siendo el tercer mayor exportador del mundo. 
Actualmente hay alrededor de 43,000 apicultores en todo el país, con más de 30% de la producción concentrada en Yucatán, Campeche y Quintana Roo: 17,000 apicultores que manejan más de 0.5 millones de colmenas. México es también uno de los mayores exportador mundial de miel orgánica en el mundo
.

####**¿Y de la apicultura en general?**

En México, la apicultura genera alrededor de 100 mil empleos directos y se producen más de 57 toneladas de miel al año, siendo Yucatán el principal productor con un aproximado de más de 8 mil toneladas anuales. Por ello debemos saber que en nuestro país, la apicultura tiene una gran importancia socioeconómica y ecológica, ya que es considerada como una de las principales actividades pecuarias.
Además, las abejas son fundamentales para un equilibrio del medio ambiente ya que las abejas al obtener el alimento de las flores fomentan en las plantas la capacidad de fecundar. Es así como se da el efecto de que las plantas puedan generar el oxígeno suficiente para la vida y aumentar el rendimiento en los cultivos, lo que favorece un incremento en alimentos de origen vegetal, materia prima textil, e insumos agropecuarios.
